### ISSUE TITLE
Create a working `snapcraft.yaml` (HELP WANTED)

### ISSUE THREAD

**Issue by luzpaz** [luzpaz/Scribus-Snap#1]
Help building a correctly formatted and constructed [snapcraft.yaml](../blob/master//snap/snapcraft.yaml).

Currently there are several working development build solutions:
* [scribus-svn](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=scribus-svn) from the AUR[^1]
* [scribus-flatpak-devel](https://codeberg.org/Scribus/scribus-flatpak-devel/raw/branch/main/net.scribus.Scribus.yaml) using flatpak[^2]
* [scribus-ci-docker](https://gitlab.com/scribus/scribus-ci-docker/-/blob/main/Dockerfile) using Docker[^3]
* AppImage `bundle.sh`[^4]
[^1]: https://aur.archlinux.org/packages/scribus-svn
[^2]: https://codeberg.org/Scribus/scribus-flatpak-devel/
[^3]: https://gitlab.com/scribus/scribus-ci-docker
[^4]: https://github.com/scribusproject/scribus/blob/master/AppImage-package/bundle.sh

**Comment by luzpaz** [comment]
**Good News:** Successfully compile FreeCAD via snapcraft.  
**Bad News:** It fails when it starts building the Snap portion of the process.

Error:
```shell
Creating snap package...
Command '['snap', 'pack', '--filename', 'scribus-git_1.7.0_amd64.snap', '--compression', 'xz', PosixPath('/build/scribus-git/prime'), PosixPath('/build/scribus-git')]' returned non-zero exit status 1.
Full execution log: '/root/.local/state/snapcraft/log/snapcraft-20241229-225625.849008.log'
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 302, in run
    self.build()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 286, in build
    self.run_build_command(["snapcraft"], cwd=output_path, env=env)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/operation.py", line 62, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 733, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-noble-amd64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/
```

**Comment by luzpaz** [comment]
Hi @nitramr, thanks for all your work on `scribus-flatpak-devel`. I just wanted to put this project, a Snap package for Scribus development, on your radar. I'm by no means a packager so this process has been tedious. I've leveraged the help of copilot and have gotten as far as I can. See previous comment for where I'm stuck. Perhaps you can lend a hand or know someone who could help ? 

I really should be building this in a virtual environment to test but that's another layer of complexity to navigate. So instead I'm leveraging the Snap store build infrastructure at https://snapcraft.io/scribus-git/builds to see if the snap indeed builds.

![Screenshot_20241230_103823](https://github.com/user-attachments/assets/2d18cdf9-986e-4ece-af64-43c9de5d98ed)

The downside is I can't read the supplemental execution log files such as `Full execution log: '/root/.local/state/snapcraft/log/snapcraft-20241229-225625.849008.log'` although i do see the build log (hence mentioned in the previous comment).

Edit: even though snap packages have their downsides, I find it to be utilitarian especially given the possibility of doing something like:  
* #2

If you're interested enough, I could also add you as a collaborator and you could have access to the infrastructure side of this snap. Let me know if you're interested?

**Comment by nitramr** [comment]
I have no experience with building snaps, but I tried to build it locally.

It seems like there are missing dependencies:
```
- library: usr/lib/x86_64-linux-gnu/libfabric.so.1.20.0: missing dependency 'libpsm_infinipath.so.1'. (provided by 'libpsm-infinipath1') (https://snapcraft.io/docs/linters-library)
- library: usr/lib/x86_64-linux-gnu/libmca_common_ofi.so.10.0.2: missing dependency 'libpsm_infinipath.so.1'. (provided by 'libpsm-infinipath1') (https://snapcraft.io/docs/linters-library)
- library: usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_btl_ofi.so: missing dependency 'libpsm_infinipath.so.1'. (provided by 'libpsm-infinipath1') (https://snapcraft.io/docs/linters-library)
- library: usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_mtl_ofi.so: missing dependency 'libpsm_infinipath.so.1'. (provided by 'libpsm-infinipath1') (https://snapcraft.io/docs/linters-library)
- library: usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi3/mca_mtl_psm.so: missing dependency 'libpsm_infinipath.so.1'. (provided by 'libpsm-infinipath1') (https://snapcraft.io/docs/linters-library)
```

I still get the error even if I add the dependencies:
      - libpsm-infinipath1
      - libpsm-infinipath1-dev

Did you try to build it locally? It generates a 9MB log file.

**Comment by luzpaz** [comment]
> Did you try to build it locally? It generates a 9MB log file.

Like i said i don't have a ton of experience with virtualization and I'm on Manjaro Linux (and don't run `apt`). 9MB log file, that's nuts.

When you say you build it locally, are you doing it in a virtual container? 

I ask because all the remote compilations have completed building scribus at 100%  
It's just the follow-up snap building portion that fails.
